config/routes.rb
Rails.application.routes.draw do
  get "bookings/new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "flights#index"
  resources :flights
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  # Associations
  has_many(
    :departing_flights,
    class_name: "Flight",
    foreign_key: "departure_airport_id"
  )

  has_many(
    :arriving_flights,
    class_name: "Flight",
    foreign_key: "arrival_airport_id"
  )

  # Validations
  validates :airport_code, uniqueness: { case_sensitive: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  # Validations
  belongs_to(
    :departure_airport,
    class_name: "Airport",
    foreign_key: "departure_airport_id"
  )

  belongs_to(
    :arrival_airport,
    class_name: "Airport",
    foreign_key: "arrival_airport_id"
  )

  has_many :bookings, dependent: :destroy
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @passenger_count = params[:passenger_count].to_i

    @booking = Booking.new
    @passenger_count.times { @booking.passengers.build }
  end

  def create
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger).booking_successful.deliver_later
      end

      redirect_to(@booking, notice: "Booking was successfully done.")
    else
      # Log the errors for debugging
      Rails.logger.error(@booking.errors.full_messages)
      @booking.passengers.each do |passenger|
        Rails.logger.error(passenger.errors.full_messages)
      end

      render(:new, status: :unprocessable_entity)
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id, :passenger_count, passengers_attributes: [ :name, :email ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @flights = Flight.all
    if params[:flight]
      if params[:flight][:departure_airport_id].present?
        @flights = @flights.where(departure_airport_id: params[:flight][:departure_airport_id])
      end

      if params[:flight][:arrival_airport_id].present?
        @flights = @flights.where(arrival_airport_id: params[:flight][:arrival_airport_id])
      end

      if params[:flight][:start_datetime].present?
        start_datetime = DateTime.parse(params[:flight][:start_datetime]).utc
        @flights = @flights.where("start_datetime >= ?", start_datetime)
      end
    end

    @passenger_count = params[:passenger_count]
  end

  private
  def flight_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :start_datetime, :passenger_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>🧳 Enter Passenger Details</h1>
<p>
<% if @flight.present? %>
  From: <%= @flight.departure_airport.airport_code %> ->
  To: <%= @flight.arrival_airport.airport_code %><br>
  When: <%= @flight.start_datetime %><br>
  Duration: <%= @flight.duration %> hrs 
<% end %>
</p>

<%= form_with(model: @booking, local: true) do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
  <% @booking.passengers.each_with_index do |passenger, index| %>
    <div>
      <h4>Passenger <%= index + 1 %></h4>
      <%= f.fields_for :passengers, passenger do |p| %>
        <div>
          <%= p.label :name, "Name" %>
          <%= p.text_field :name %>
        </div>
        <div>
          <%= p.label :email, "Email" %>
          <%= p.email_field :email %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= f.submit "Create Booking" %>
<% end %>

app/views/bookings/show.html.erb
<h2>📅 Booking Details</h2>

<p>
<% if @flight.present? %>
  From: <%= @flight.departure_airport.airport_code %> ->
  To: <%= @flight.arrival_airport.airport_code %><br>
  When: <%= @flight.start_datetime %><br>
  Duration: <%= @flight.duration %> hrs 
<% end %>

</p>

<h3>Passengers</h3>
<ol>
  <% @booking.passengers.each do |passenger| %>
    <li>
      <strong>Name:</strong> <%= passenger.name %><br>
      <strong>Email:</strong> <%= passenger.email %>
    </li>
  <% end %>
</ol>

app/views/flights/index.html.erb
<h1>✈️ Flights</h1>

<%= form_with(url: flights_path, method: :get, local: true) do %>
  <p>Departure from: </p>
  <select name="flight[departure_airport_id]">
    <% @airports.each do |airport| %>
      <option value="<%= airport.id%>"><%= airport.airport_code %></option> 
    <% end %>
  </select>

  <p>Arrival to: </p>
  <select name="flight[arrival_airport_id]">
    <% @airports.each do |airport| %>
      <option value="<%= airport.id%>"><%= airport.airport_code %></option> 
    <% end %>
  </select>

  <p>Travelling on: </p>
  <select name="flight[start_datetime]">
    <% @flights.pluck(:start_datetime).uniq.each do |datetime| %>
      <option value="<%= datetime %>"><%= datetime %></option>
    <% end %>
  </select>

  <p>Passengers: </p>
  <select name="passenger_count">
    <option value="1">1</option> 
    <option value="2">2</option> 
    <option value="3">3</option> 
    <option value="4">4</option> 
  </select>

  <%= submit_tag "Search" %>
<% end %>


<%= form_with(url: "/bookings/new", method: :get, local: true) do %>
  <h4>Available flights: </h4>
  <% if @flights.present? %>
    <% @flights.each do |flight| %>
      <div>
        <label>
          <%= radio_button_tag 'flight_id', flight.id %>
          From: <%= flight.departure_airport.airport_code %> ->
          To: <%= flight.arrival_airport.airport_code %><br>
          When: <%= flight.start_datetime %><br>
          Duration: <%= flight.duration %> hrs 
        </label>
      </div>
    <% end %>
    <%= hidden_field_tag 'passenger_count', @passenger_count %>
    <%= submit_tag "Book flight" %>
  <% else %>
    <p>No flights available for the selected criteria.</p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>